shell-check fixes, clean up aliases, smarter passman
Moved some functions out of aliases, alphabetized aliases, cleaned up passman stuff, only ask for passman auth when needed, fixes to workstation update, shell-check changes

diff --git a/home/.bashrc.d/0alias b/home/.bashrc.d/0alias
--- a/home/.bashrc.d/0alias
+++ b/home/.bashrc.d/0alias
@@ -22,22 +22,53 @@ alias cdd="homeshick cd dotfiles"
 alias cdp="homeshick cd dotfiles_private"
 alias pp="source ~/.bash_profile"
 
-function pathadd() {
-  unset newpath
-  local newpath=${1%/}
-  if [[ ! -d "${newpath}" ]] ; then
-    # echo "Directory \"${1}\" does not exist."
-    return
+function acp {
+  cp -av ${1} ${1}.$(date --rfc-3339=date)
+}
+
+function bashcurl {
+  # utilizes https://stackoverflow.com/questions/5951029/read-http-output-using-shell-bash-script
+  local URL=${1}
+  local tag="Connection: close"
+  local mark=0
+
+  if [[ -z "${URL}" ]]; then
+    printf "Usage: %s \"URL\" [e.g.: %s http://www.google.com/]" \
+      "${FUNCNAME[0]}" "${FUNCNAME[0]} \
+      "
+    return 1;
+  elif ! [[ "${URL}" =~ "https://" ]]; then
+    URL="https://${URL}"
+    echo "Updated \${URL} to \"${URL}\""
   fi
-  if [[ "${PATH}" =~ (^|:)"${newpath}"(:|$) ]] ; then
-    # echo "Path \"${newpath}\" already exists in path \"${PATH}\"."
-    return
-  fi
-  if [[ "${2}" == "after" ]] ; then
-    export PATH="${PATH}:${newpath}"
-  else
-    export PATH="${newpath}:${PATH}"
-  fi
+  read proto server path <<<$(echo ${URL//// })
+  DOC=/${path// //}
+  HOST=${server//:*}
+  PORT=${server//*:}
+  [[ x"${HOST}" == x"${PORT}" ]] && PORT=80
+  [[ ${VERBOSE} -ge 1 ]] && echo "HOST=${HOST}"
+  [[ ${VERBOSE} -ge 1 ]] && echo "PORT=${PORT}"
+  [[ ${VERBOSE} -ge 1 ]] && echo "DOC=${DOC}"
+
+  exec 5<>/dev/tcp/${HOST}/${PORT}
+  echo -en "GET ${DOC} HTTP/1.1\r\nHost: ${HOST}\r\n${tag}\r\n\r\n" >&5
+  while read line; do
+    [[ $mark -eq 1 ]] && echo ${line}
+    if [[ "${line}" =~ "${tag}" ]]; then
+      mark=1
+    fi
+  done <&5
+  exec 5>&-
+}
+
+function find-error() {
+  sudo grep -A2 -B2 -riHE 'DENIED|ERR|EXIST|FAIL|INVALID|SPECIFIED|SUCH|UNABLE|WARN|USAGE:|UNKNOWN|:\ LINE\ [0-9]' ${1} \
+  | grep -v ierra \
+  | grep -v erra
+}
+
+function joke() {
+  curl https://icanhazdadjoke.com; echo
 }
 
 function port {
@@ -71,50 +102,27 @@ function port {
     || (>&2 echo "failure"; return 1)
 }
 
-function bashcurl {
-  # utilizes https://stackoverflow.com/questions/5951029/read-http-output-using-shell-bash-script
-  : ${DEBUG:=0}
-  local URL=${1}
-  local tag="Connection: close"
-  local mark=0
-
-  if [[ -z "${URL}" ]]; then
-    printf "Usage: %s \"URL\" [e.g.: %s http://www.google.com/]" \
-      "${FUNCNAME[0]}" "${FUNCNAME[0]} \
-      "
-    return 1;
-  elif ! [[ "${URL}" =~ "https://" ]]; then
-    URL="https://${URL}"
-    echo "Updated \${URL} to \"${URL}\""
+function _throttle()
+{
+  if [[ "${#}" -lt 2 ]]; then
+    printf '%s\n' "Usage: throttle timeout command [arg ... ]" >&2
+    return 1
   fi
-  read proto server path <<<$(echo ${URL//// })
-  DOC=/${path// //}
-  HOST=${server//:*}
-  PORT=${server//*:}
-  [[ x"${HOST}" == x"${PORT}" ]] && PORT=80
-  [[ ${DEBUG} -eq 1 ]] && echo "HOST=${HOST}"
-  [[ ${DEBUG} -eq 1 ]] && echo "PORT=${PORT}"
-  [[ ${DEBUG} -eq 1 ]] && echo "DOC =${DOC}"
+  local t=${1}
+  shift
 
-  exec 5<>/dev/tcp/${HOST}/${PORT}
-  echo -en "GET ${DOC} HTTP/1.1\r\nHost: ${HOST}\r\n${tag}\r\n\r\n" >&5
-  while read line; do
-    [[ $mark -eq 1 ]] && echo ${line}
-    if [[ "${line}" =~ "${tag}" ]]; then
-      mark=1
+  [[ ${VERBOSE} -ge 1 ]] && \
+    echo "starting throttle function with t=${t} and _throttled=${_throttled}"
+
+  if [[ -n "${_throttled["${1}"]}" ]]; then
+    if [[ "$(date +%s)" -ge "${_throttled["${1}"]}" ]]; then
+      "${@}" && _throttled["${1}"]=$((t + $(date +%s)))
+    else
+      : printf '%s\n' "Timeout for: ${1} has not yet been reached" >&2
     fi
-  done <&5
-  exec 5>&-
-}
-
-function acp {
-  cp -av ${1} ${1}.$(date --rfc-3339=date)
-}
-
-function find-error() {
-  sudo grep -A2 -B2 -riHE 'DENIED|ERR|EXIST|FAIL|INVALID|SPECIFIED|SUCH|UNABLE|WARN|USAGE:|UNKNOWN|:\ LINE\ [0-9]' ${1} \
-  | grep -v ierra \
-  | grep -v erra
+  else
+    "${@}" && _throttled["${1}"]=$((t + $(date +%s)))
+  fi
 }
 
 if [[ "${IS_MACOS}" == "true" ]]; then
@@ -129,68 +137,14 @@ if [[ "${IS_MACOS}" == "true" ]]; then
   # alias gphoto="open --background -a \"Google Photos Backup\""
   # alias gphoto="open --background -a \"Backup and Sync\""
 
-  function _throttle()
-  {
-    if [[ "${#}" -lt 2 ]]; then
-      printf '%s\n' "Usage: throttle timeout command [arg ... ]" >&2
-      return 1
-    fi
-    local t=${1}
-    shift
-
-    [[ ${VERBOSE} -ge 1 ]] && \
-      echo "starting throttle function with t=${t} and _throttled=${_throttled}"
-
-    if [[ -n "${_throttled["${1}"]}" ]]; then
-      if [[ "$(date +%s)" -ge "${_throttled["${1}"]}" ]]; then
-        "${@}" && _throttled["${1}"]=$((t + $(date +%s)))
-      else
-        : printf '%s\n' "Timeout for: ${1} has not yet been reached" >&2
-      fi
-    else
-      "${@}" && _throttled["${1}"]=$((t + $(date +%s)))
-    fi
+  function ack {
+    $(which ack) "${@}" --ignore-dir=.terraform
   }
 
-  # https://github.com/chubin/awesome-console-services
-  function speedtest {
-    curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py \
-    | python - --secure --simple --single
-    # includes bufferbloat score: http://www.dslreports.com/speedtest
-  }
-
-  function whatismyip {
-    curl ifconfig.me
-  }
-
-  function netshoot {
-    # spin up a throwaway container in k8s for network debugging
-    kubectl --kubeconfig ~/.kube/${1} run --generator=run-pod/v1 \
-      tmp-shell --rm -i --tty --image nicolaka/netshoot -- /bin/bash
-  }
-
-  function mysql-client {
-    # spin up a throwaway container in k8s for querying RDS
-    kubectl --kubeconfig ~/.kube/${1} run --generator=run-pod/v1 \
-      tmp-shell --rm -i --tty --image arey/mysql-client -- \
-        mysql -P3306 -h"${2}.us-east-1.rds.amazonaws.com" -u"user1" -p"SeeLastPass"
-    # docker run --rm -it alpine:latest sh
-    #   apk add bash mysql-client
-    #   mysql -h"something.us-east-1.rds.amazonaws.com" -P"3306" -u"user1" -p"SeeLastPass"
-
-  }
-
-  function weather {
-    curl https://wttr.in/Denver
-  }
-
-  function update-all-repos {
-    for repo1 in $(find ~/build/github -mindepth 1 -maxdepth 6 -path "*/.git/config") ; do echo -e "\n${repo1%.git/config}" ; \
-      cd ${repo1%.git/config} \
-      && git clean -xfd \
-      && gitp \
-      && cd - ; \
-    done
+  function alfred {
+    passman  "${CUSTOM_WORK_DOMAINS[0]/.com/} macbook" || echo "Unable to cache pw."
+    $(which alfred) ${*}
+    # $(which alfred) "${@}"
   }
 
   function argod () {
@@ -219,26 +173,6 @@ if [[ "${IS_MACOS}" == "true" ]]; then
     cd ~/build/github/${@}
   }
 
-  function passman() {
-    # TODO: convert to flag based args instead of positional args
-    # # if the first variable is an integer, then clear clipboard
-    # local clear_clip_delay
-    # if [[ ${1} =~ ^-?[0-9]+$ ]] ; then
-    #   clear_clip_delay=${1}
-    # fi
-    local item1="${1}"
-    shift
-    local field1="${@:-password}" # default to grabbing password
-
-    [[ ${VERBOSE} -ge 1 ]] && \
-      echo "Running: op get item \"${item1}\" --fields \"${field1}\" | pbcopy"
-    op get item "${item1}" --fields "${field1}" | pbcopy
-
-    # if [[ ${clear_clip_delay} -gt 0 ]]; then
-    #   clear_clip ${1}
-    # fi
-  }
-
   function clear_clip {
     # clear clipboard after N seconds
     local wait_time="${1:-0}"
@@ -250,95 +184,44 @@ if [[ "${IS_MACOS}" == "true" ]]; then
     ) 2> /dev/null
   }
 
-  function otp {
-    [[ ${VERBOSE} -ge 1 ]] && \
-      echo "Running: op get totp \"${1}\" | cut -c1-6 | tr -d '\n' | pbcopy"
-    op get totp "${1}" | cut -c1-6 | tr -d '\n' | pbcopy
-    # otp-cli show -1 -c -s ${CUSTOM_WORK_SSO_PROVIDER} | awk '/[0-9].*/{print $2}'
-  }
-
-  function session_is_active {
-    # usage: session_is_active <tool_name> [<session_validity_length>]
-    # ex1: if $(session_is_active saml2aws); then echo "already active session"; fi
-    # description: return 0 if a tool's session token is active, else 1
-    #  To reduce the number of unnecessary authentication calls (which can be slow)
-    #  when other native mechanisms to check don't exist. If necessary, sets up a
-    #  local hidden file with a timestamp in it of an expiration date. If the file
-    #  already exists and the date is in the future, simply returns false. This will
-    #  not store token values for the tool's session.
-
-    local current_time=$(/usr/local/opt/coreutils/libexec/gnubin/date +%s)
-
-    local tool_name="${1}"
-    local timeout_file="/var/tmp/.${tool_name}_token_expiration"
-    shift
-    local expiration_date
-
-    if [[ -n "${*}" ]]; then
-      # session_validity_length provided; need to setup expiration file
-      # if [[ ${VERBOSE} -ge 1 ]]; then
-      #   echo "Creating expiration date from \$(/usr/local/opt/coreutils/libexec/gnubin/date --date=\"${*}\" +%s)"
-      # fi
-      expiration_date=$(/usr/local/opt/coreutils/libexec/gnubin/date --date="${*}" +%s)
-      if ! [[ ${expiration_date} =~ ^-?[0-9]+$ ]]; then
-        echo "Unable to create expiration date from \"${*}\"."
-        return 1
-      fi
-      # if [[ ${VERBOSE} -ge 1 ]]; then
-      #   echo "Creating token expiration file for ${tool_name} with value of ${expiration_date}"
-      # fi
-      (umask 077 ; touch "${timeout_file}")
-      # $(brew --prefix coreutils)/libexec/gnubin/chmod -c 600 ${timeout_file}
-      echo "${expiration_date}" > "${timeout_file}"
-      return 0
-    else
-      # if [[ ${VERBOSE} -ge 1 ]]; then
-      #   echo "grab existing date from tools token expiration file and see if active"
-      # fi
-      if [[ -f ${timeout_file} && -s ${timeout_file} ]]; then
-        # if [[ ${VERBOSE} -ge 1 ]]; then
-        #   echo "${tool_name} token expiration file found; grabbing expiration time"
-        # fi
-        expiration_date=$(head -n1 "${timeout_file}")
-        if [[ ${expiration_date} =~ ^-?[0-9]+$ && \
-        ${expiration_date} > ${current_time} ]]; then
-          # if [[ ${VERBOSE} -ge 1 ]]; then
-          #   echo "\"${expiration_date}\" is > \"${current_time}\""
-          # fi
-          return 0
-        else
-          # if [[ ${VERBOSE} -ge 1 ]]; then
-          #   echo "\"${expiration_date}\" is <= \"${current_time}\""
-          # fi
-          return 1
-        fi
-      else
-        # can't find the file or expiration date so we do actually need to set it up
-        echo "Fatal error: ${timeout_file} not found or empty"
-        return 1
-      fi
-    fi
-  }
-
-  function rsync {
-    echo "Running: time $(which rsync) -axHAWXS --info=progress2 --numeric-ids --size-only ..."
-    time $(which rsync) -axHAWXS --partial --info=progress2 --numeric-ids --size-only ${@}
-    # ttime $(which rsync) -axHAWXSP --numeric-ids --size-only ${@}
-  }
-
-  function alfred {
-    passman  "${CUSTOM_WORK_DOMAINS[0]/.com/} macbook" || echo "Unable to cache pw."
-    $(which alfred) ${*}
-    # $(which alfred) "${@}"
-  }
-
   function keybase {
     passman  "Keybase" || echo "Unable to cache pw."
     $(which keybase) ${*}
   }
 
-  function ack {
-    $(which ack) "${@}" --ignore-dir=.terraform
+  function mysql-client {
+    # spin up a throwaway container in k8s for querying RDS
+    kubectl --kubeconfig ~/.kube/${1} run --generator=run-pod/v1 \
+      tmp-shell --rm -i --tty --image arey/mysql-client -- \
+        mysql -P3306 -h"${2}.us-east-1.rds.amazonaws.com" -u"user1" -p"SeeLastPass"
+    # docker run --rm -it alpine:latest sh
+    #   apk add bash mysql-client
+    #   mysql -h"something.us-east-1.rds.amazonaws.com" -P"3306" -u"user1" -p"SeeLastPass"
+  }
+
+  function openit {
+    # quickly opens macos programs in the background if not already running
+    local -a programs=("${@}")
+    local program1
+    local -i item
+
+    for ((item = 0; item < ${#programs[@]}; item++)); do
+      program1="${programs[${item}]}"
+      pgrep -qf "${program1}.app" || (nohup open --hide --background -a "${program1}" </dev/null >/dev/null 2>&1 &)
+    done
+  }
+
+  function rsync {
+    echo "Running: time $(which rsync) -axHAWXS --info=progress2 --numeric-ids --size-only ${@}"
+    time $(which rsync) -axHAWXS --partial --info=progress2 --numeric-ids --size-only ${@}
+    # ttime $(which rsync) -axHAWXSP --numeric-ids --size-only ${@}
+  }
+
+  # https://github.com/chubin/awesome-console-services
+  function speedtest {
+    curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py \
+    | python - --secure --simple --single
+    # includes bufferbloat score: http://www.dslreports.com/speedtest
   }
 
   if [[ ${TRAVIS_CI_RUN} != true ]]; then
@@ -367,16 +250,12 @@ if [[ "${IS_MACOS}" == "true" ]]; then
     }"
   fi
 
-  function openit {
-    # quickly opens macos programs in the background if not already running
-    local -a programs=("${@}")
-    local program1
-    local -i item
+  function whatismyip {
+    curl ifconfig.me
+  }
 
-    for ((item = 0; item < ${#programs[@]}; item++)); do
-      program1="${programs[${item}]}"
-      pgrep -qf "${program1}.app" || (nohup open --hide --background -a "${program1}" </dev/null >/dev/null 2>&1 &)
-    done
+  function weather {
+    curl https://wttr.in/Denver
   }
 elif [[ "${IS_LINUX}" == "true" ]]; then
   alias ls="ls --color=auto"
diff --git a/home/.bashrc.d/k8s b/home/.bashrc.d/k8s
--- a/home/.bashrc.d/k8s
+++ b/home/.bashrc.d/k8s
@@ -1,14 +1,19 @@
 [[ $- = *i* ]] || return
 ${IS_MACOS} || return
 
+$(/usr/local/bin/brew --prefix findutils)/libexec/gnubin/find ~/.kube/ \
+  -mindepth 1 \
+  -maxdepth 1 \
+  -type l \
+  -exec chmod -c 600 '{}' \;
 # export KUBECONFIG=~/.kube/k3sa
- export KUBECONFIG=$(find ~/.kube/ \
-   -mindepth 1 \
-   -maxdepth 1 \
-   -type l \
-   ! -name minikube \
-   | sort \
-   | tr '\n' ':')
+export KUBECONFIG=$(find ~/.kube/ \
+  -mindepth 1 \
+  -maxdepth 1 \
+  -type l \
+  ! -name minikube \
+  | sort \
+  | tr '\n' ':')
   # -printf "%p:" \
 
 # source <(kubectl completion bash) # slow
@@ -28,7 +33,7 @@ function k() {
 
   local my_aws_profile="$(map-cluster-to-profile ${cluster})"
   # verify that eks clusters mapped to a my_aws_profile
-  if [[ ! ${cluster} =~ k8s ]] && [[ "${my_aws_profile}" == "" ]]; then
+  if [[ "${my_aws_profile}" == "" ]]; then
     return 1
   fi
   # if ! $(on_vpn); then
@@ -48,11 +53,7 @@ function k() {
     *get?po*)
       action="${action} --sort-by=.metadata.creationTimestamp" ;;
     *get?no*)
-      if [[ ${cluster} =~ k8s ]]; then
-        action="${action} --label-columns=kubernetes.io/role,function --sort-by=.metadata.creationTimestamp"
-      else
-        action="${action} --label-columns=nodegroup_name,function --sort-by=.metadata.creationTimestamp"
-      fi ;;
+      action="${action} --label-columns=nodegroup_name,function --sort-by=.metadata.creationTimestamp" ;;
     *)
       [[ ${VERBOSE} -ge 1 ]] && echo "matched global"
       action="${action}" ;;
@@ -61,6 +62,40 @@ function k() {
   [[ ${VERBOSE} -ge 1 ]] && \
     echo "Running: \"$(which kubectl) ${kube_config} ${action}\""
   kubectl ${kube_config} ${action} #--context admin@${cluster}
+}
+
+function h() {
+  local cluster=${1}
+  if ! [[ -r ~/.kube/${cluster} ]]; then
+    echo "No kubeconfig found for \"${cluster}\"!"
+    return 1
+  fi
+  shift
+  local action=${@} # ex: "get pod"
+
+  local my_aws_profile="$(map-cluster-to-profile ${cluster})" # dynamically determine
+
+  # verify that eks clusters mapped to an my_aws_profile
+  if [[ "${my_aws_profile}" == "" ]]; then
+    echo "Could not map the cluster name to an aws profile."
+    return 1
+  fi
+  # if ! $(on_vpn); then
+  #   work_vpn
+  #   echo
+  # fi
+
+  local kube_config="--kubeconfig ${HOME}/.kube/${cluster}"
+  local helm_path="$(asdf where helm)/bin/helm"
+  [[ ${VERBOSE} -ge 1 ]] && \
+    echo "Running: \"${helm_path} ${kube_config} ${action}\""
+  ${helm_path} ${kube_config} ${action} #--kube-context admin@${cluster}
+}
+
+function netshoot {
+  # spin up a throwaway container in k8s for network debugging
+  kubectl --kubeconfig ~/.kube/${1} run --generator=run-pod/v1 \
+    tmp-shell --rm -i --tty --image nicolaka/netshoot -- /bin/bash
 }
 
 function ibexs() {
@@ -84,44 +119,6 @@ function ibexs() {
   ./ibex --cluster ${my_cluster_path} ${args}
 }
 
-function h() {
-  local cluster=${1}
-  if ! [[ -r ~/.kube/${cluster} ]]; then
-    echo "No kubeconfig found for \"${cluster}\"!"
-    return 1
-  fi
-  shift
-  local action=${@} # ex: "get pod"
-
-  local my_aws_profile="$(map-cluster-to-profile ${cluster})" # dynamically determine
-
-  # verify that eks clusters mapped to an my_aws_profile
-  if [[ ! ${cluster} =~ k8s ]] && [[ "${my_aws_profile}" == "" ]]; then
-    echo "Could not map the cluster name to an aws profile."
-    return 1
-  fi
-  # if ! $(on_vpn); then
-  #   work_vpn
-  #   echo
-  # fi
-
-  local kube_config="--kubeconfig ${HOME}/.kube/${cluster}"
-
-  # old kops clusters dont need saml2aws wrapper
-  # local wrapper="saml2aws exec --exec-profile=${my_aws_profile} --"
-  local helm_path="/Users/${LOGNAME}/.asdf/shims/helm"
-  if [[ ${cluster} =~ k8s ]]; then
-    wrapper=""
-    # kops clusters (k8s and k8s-staging) running helm 2.14.2
-    asdf install helm 2.14.2
-    helm_path="$(asdf where helm 2.14.2)/bin/helm"
-  fi
-
-  [[ ${VERBOSE} -ge 1 ]] && \
-    echo "Running: \"${helm_path} ${kube_config} ${action}\""
-  ${helm_path} ${kube_config} ${action} #--kube-context admin@${cluster}
-}
-
 # kubectl plugin manager: krew
 export KREW_ROOT=${HOME}/.krew
 pathadd ${KREW_ROOT}/bin
@@ -143,47 +140,6 @@ function _get_latest_version_from_github()
     return 1
   fi
 }
-function get_kube_versions()
-{
-  # mostly replaced by kubectl/krew outdated and FairwindsOps/nova
-  local L8ST_COREOS_V=$(curl -s https://coreos.com/dist/aws/aws-stable.json \
-    | jq -r '.release_info.version') \
-  local CURR_KOPS_V=$(kops version | awk '{print $2}') \
-  local L8ST_KOPS_V=$(_get_latest_version_from_github "kubernetes/kops")
-  local CURR_K8S_V=$(kubectl version --short --output=json | jq -r '.serverVersion.gitVersion')
-  local L8ST_K8S_V=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
-  local CURR_HELMC_V=$(helm version --client --short | awk '{print $2}')
-  local CURR_HELMS_V=$(helm version --server --short | awk '{print $2}')
-  local L8ST_HELM_V=$(_get_latest_version_from_github "helm/helm")
-  # TODO: GO_V=$(kubectl version --short --output=json | jq -r '.serverVersion.goVersion')
-  # TODO: Versions of kernel, Debian/coreos/container-optimized-os-from-google, etcd, kube-aws,
-  #  kiam-server, kernel, nginx ingress, dashboard, heapster->metrics-server, kube-state-metrics, prometheus, eksctl?
-  # TODO: providers for dns and network layer
-  # datadog agent+chart, sumologic-fluentd agent+chart, runatlantis/atlantis
-  # update di-4325
-
-  ### Tools that come with the cluster (indirect versioning correlation)
-  # docker: https://github.com/docker/docker-ce/releases/latest
-  # cluster-autoscaler latest version matches k8s: https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases
-  # kube-state-metrics: https://github.com/kubernetes/kube-state-metrics#compatibility-matrix
-
-  # TODO: utilize column command?
-  cat << TABLE_EOF
-  +------------+------------------+----------------+
-  | COMPONENT  | CURRENT VERSION  | LATEST VERSION |
-  +------------+------------------+----------------+
-  | CoreOS     | N/A              | ${L8ST_COREOS_V}       |
-  +------------+------------------+----------------+
-  | Kops       | ${CURR_KOPS_V}           | ${L8ST_KOPS_V}         |
-  +------------+------------------+----------------+
-  | Kubernetes | ${CURR_K8S_V}          | ${L8ST_K8S_V}        |
-  +------------+------------------+----------------+
-  | Helm Client| ${CURR_HELMC_V} | ${L8ST_HELM_V}        |
-  +------------+------------------+----------------+
-  | Helm Server| ${CURR_HELMS_V} | ${L8ST_HELM_V}        |
-  +------------+------------------+----------------+
-TABLE_EOF
-}
 
 # function doit () {
 #   local saml2aws-profile=${1}
@@ -197,6 +153,16 @@ TABLE_EOF
 #         kubectl get nodes -o go-template --template=\'{{.spec.externalID}}\' ${nodeid}
 #   done
 # }
+
+# if one AZ is having problems in EC2...
+# 1) Use datadog to look at all errors in a cluster per AZ to find the one that is having problems
+# 2) If running spot ASGs (which span multi AZ), simply remove the bad AZ subnet from its config in the console
+# 3) cordon and drain those nodes from the cluster
+# [optional] kubectl cordon -l 'failure-domain.beta.kubernetes.io/zone=us-east-1d'
+# kubectl drain --ignore-daemonsets --delete-local-data -l 'failure-domain.beta.kubernetes.io/zone=us-east-1d'
+# repeat the drain as necessary to catch any new nodes coming up in the bad AZ
+# 4) If running ASGs per AZ, decrease the max nodes to the same as the running nodes and min to 0 (so no new ones can spin up)
+#  watch for race condition between decreasing max and cluster-autoscaler not knowing to prevent launching in bad az
 
 # kubectl get node \
   # -l kubernetes.io/role=node,failure-domain.beta.kubernetes.io/zone=us-east-${az} \
@@ -230,3 +196,11 @@ TABLE_EOF
 
 # show counts of unique images/version for kubelet
 # kubectl --kubeconfig get no --sort-by=.metadata.creationTimestamp -o jsonpath='{..kubeletVersion}' | tr -s '[[:space:]]' '\n' | sort | uniq -c
+
+# show all pods from nodes with given label
+# pcols=""; for n in $(kubectl get node -lfunction=cluster-critical -ocustom-columns=name:metadata.name --no-headers); do kubectl get pod \
+# --all-namespaces -o wide --field-selector "spec.nodeName=$n" $pcols; pcols="--no-headers"; done | column -t
+
+# show Pods with containers that aren't ready. Each row is the pod name, container name, ready state, started state.
+# kubectl get pod --all-namespaces -o go-template='POD{{"\t"}}CONTAINER{{"\t"}}READY{{"\t"}}STARTED{{"\n"}}{{range .items}}{{$p:=.metadata.name}}{{range \
+# .status.containerStatuses}}{{if not .ready}}{{$p}}{{"\t"}}{{.name}}{{"\t"}}{{.ready}}{{"\t"}}{{.started}}{{"\n"}}{{end}}{{end}}{{end}}'
