Rename saml2aws override, disable krew
Update aws and eks utils
Verbose port utility

diff --git a/home/.bashrc.d/0alias b/home/.bashrc.d/0alias
--- a/home/.bashrc.d/0alias
+++ b/home/.bashrc.d/0alias
@@ -97,7 +97,9 @@ function port {
     return 1
   fi
 
-  # echo "Checking host \"${host1}\" over port \"${port1}\"."
+  [[ ${VERBOSE} -ge 1 ]] && \
+    echo "Running: ${timeout_path} 2 bash -c \"echo >/dev/tcp/${host1}/${port1}\" > /dev/null 2>&1 && echo success \
+    || (>&2 echo \"failure\"; return 1)"
   ${timeout_path} 2 bash -c "echo >/dev/tcp/${host1}/${port1}" > /dev/null 2>&1 && echo success \
     || (>&2 echo "failure"; return 1)
 }
