smarter port function, smarter vault communication, go back to forked liquidprompt with k8s info

diff --git a/home/.bashrc.d/aaalias b/home/.bashrc.d/aaalias
--- a/home/.bashrc.d/aaalias
+++ b/home/.bashrc.d/aaalias
@@ -58,7 +58,34 @@ function _create_socks_proxy {
 }
 
 function port {
-  timeout 2 bash -c "echo >/dev/tcp/${1}/{2}" > /dev/null 2>&1 && echo success || echo failure
+  # strip http.* from parameter
+  local host1=${1#*//}
+  # find port from either "server1:1234" or "server1 1234"
+  local port1
+  if [[ -n ${2} ]] && [[ ${host1} =~ ":" ]]; then
+    (>&2 echo "  detected multiple port inputs; using ${2}")
+    port1=${2}
+    # strip port from host variable
+    host1=${host1%:*}
+  elif [[ -n ${2} ]]; then
+    port1=${2}
+  elif [[ -z ${2} ]] && [[ ${host1} =~ ":" ]]; then
+    port1=${host1#*:}
+    # strip port from host variable
+    host1=${host1%:*}
+  elif [[ -z ${2} ]] && [[ ! ${host} =~ ":" ]]; then
+    (>&2 echo "You must supply a port number as an additional parameter or append \":1234\".")
+    return 1
+  fi
+
+  if ! [[ "${port1}" =~ ^[0-9]+$ ]]; then
+    (>&2 echo "You supplied an incorrect port.")
+    return 1
+  fi
+
+  # echo "Checking host \"${host1}\" over port \"${port1}\"."
+  timeout 2 bash -c "echo >/dev/tcp/${host1}/${port1}" > /dev/null 2>&1 && echo success \
+    || (>&2 echo "failure"; return 1)
 }
 
 function acp {
diff --git a/home/.bashrc.d/aaavault b/home/.bashrc.d/aaavault
--- a/home/.bashrc.d/aaavault
+++ b/home/.bashrc.d/aaavault
@@ -1,19 +1,22 @@
 ${IS_OSX} || return
 
 export VAULT_REACHABLE="true"
-$(port ${VAULT_ADDR} &> /dev/null) || VAULT_REACHABLE="false"
-
 export VAULT_ADDR="https://vault.${CUSTOM_WORK_DOMAINS[2]}:8200"
-# export VAULT_MFA=#TODO
 export VAULT_CLIENT_TIMEOUT=2
+# export VAULT_MFA=#TODO
+
+# TODO: this port check is expensive; only check if token lookup fails?
+port ${VAULT_ADDR} &> /dev/null || VAULT_REACHABLE="false"
 
 # vault authentication, if available and necessary
-if ${HEALTHY_INTERNET} && ${VAULT_REACHABLE} && ! vault token lookup &> /dev/null; then
-  echo "Must re-authenticate with VAULT (${VAULT_ADDR}...)"
-  lpass show --password --clip LDAP
-  vault login -method=ldap username=${CUSTOM_LDAP_NAME} > /dev/null
-  vault token renew -increment=10h > /dev/null
-  clear_clip
+if [[ "${HEALTHY_INTERNET}" == "true" ]] && [[ "${VAULT_REACHABLE}" == "true" ]]; then
+  if ! vault token lookup &> /dev/null; then
+    echo "Must re-authenticate with VAULT (${VAULT_ADDR}...)"
+    lpass show --password --clip LDAP
+    vault login -method=ldap username=${CUSTOM_LDAP_NAME} > /dev/null
+    vault token renew -increment=10h > /dev/null
+    clear_clip
+  fi
 else
-  echo "Skipping vault auth as it is unreachable."
+  (>&2 echo "Skipping vault auth as it is unreachable.")
 fi
diff --git a/home/.bashrc.d/k8s b/home/.bashrc.d/k8s
--- a/home/.bashrc.d/k8s
+++ b/home/.bashrc.d/k8s
@@ -10,21 +10,21 @@ export KOPS_STATE_STORE="s3://webrtc-gateway-kops-state"
 function set_kube_current_config()
 {
   if [[ ${VAULT_REACHABLE} != "true" ]]; then
-    echo "Skipping set_kube_current_config as vault is unreachable..."
+    (>&2 echo "Skipping set_kube_current_config as vault is unreachable...")
     return 1
   fi
-  
+
   local kops_name="${@}"
   if [[ -z ${kops_name} ]]; then
-    echo "You did not provide a default kops name argument."
+    (>&2 echo "You did not provide a default kops name argument.")
     return 1
   fi
   if [[ ${kops_name} =~ "\." ]]; then
-    echo "You did not provide a fully qualified kops name argument."
+    (>&2 echo "You did not provide a fully qualified kops name argument.")
     return 1
   fi
   if [[ -z $(kubectl config current-context) ]];then
-    echo "\"kubectl config current-context\" is blank!"
+    (>&2 echo "\"kubectl config current-context\" is blank!")
     return 1
   fi
 
@@ -50,19 +50,19 @@ function set_kube_current_config_old()
 {
   local kops_name="${@}"
   if [[ -z ${kops_name} ]]; then
-    echo "You did not provide a default kops name argument."
+    (>&2 echo "You did not provide a default kops name argument.")
     return 1
   fi
   if [[ ${kops_name} =~ "\." ]]; then
-    echo "You did not provide a fully qualified kops name argument."
+    (>&2 echo "You did not provide a fully qualified kops name argument.")
     return 1
   fi
   if [[ -z ${KOPS_STATE_STORE} ]]; then
-    echo "\${KOPS_STATE_STORE} is blank; unable to retrieve kubeconfig from s3."
+    (>&2 echo "\${KOPS_STATE_STORE} is blank; unable to retrieve kubeconfig from s3.")
     return 1
   fi
   if [[ -z $(kubectl config current-context) ]];then
-    echo "\"kubectl config current-context\" is blank!"
+    (>&2 echo "\"kubectl config current-context\" is blank!")
     return 1
   fi
   kops export kubecfg --name $(kubectl config current-context)
