Many improvements
Added netshoot utility function
Added gnu-sed to PATH
Load work ssh keys only if necessary
Specify IAM role for saml2aws
Smarter kubectl overrides
Smarter detection of vpn connectivity
workstation setup script updates
Fixed bug in workstation update

diff --git a/home/.bashrc.d/aws b/home/.bashrc.d/aws
--- a/home/.bashrc.d/aws
+++ b/home/.bashrc.d/aws
@@ -9,14 +9,23 @@ export SAML2AWS_SESSION_DURATION=43200 # 12 hour max for "saml2aws login"
 
 function saml2aws {
   # saml2aws logins can have a max session duration of 12h, but role chaining can only have a max session duration of 1h
-  local session_dur="--session-duration=${SAML2AWS_SESSION_DURATION}"
+  local args="--session-duration=${SAML2AWS_SESSION_DURATION} \
+    --role=${CUSTOM_WORK_IAM_ROLE}"
   if [[ ${@} =~ "--exec-profile" ]] ; then
     export MY_AWS_PROFILE=$(echo ${@} | sed -r 's/.*--exec-profile[=,\ ]([^ ]+).*/\1/')
-    session_dur="--session-duration=3600"
+    args="--session-duration=3600"
   fi
-  lpass show --password --clip "${CUSTOM_WORK_DOMAINS[0]/.com/} macbook" || echo "Unable to cache pw."
-  # echo "Running \"saml2aws ${session_dur} --skip-prompt ${*}\""
-  $(which saml2aws) ${session_dur} --skip-prompt ${*}
+  # if [[ ${@} =~ "helmfile" || ${@} =~ "tf-" ]] ; then
+  #   # "need to cache work private ssh key"
+  #   lpass show --field=Passphrase --clip "id_rsa"
+  # fi
+  # lpass show --password --clip "${CUSTOM_WORK_DOMAINS[0]/.com/} macbook" || echo "Unable to cache pw."
+  # echo "Running \"saml2aws ${args} --skip-prompt ${*}\""
+  $(which saml2aws) ${args} --skip-prompt ${*}
+}
+
+function samllogin {
+  saml2aws login
 }
 
 function get-ec2-id-from-pod ()
