Reverting forked liquidprompt (moved customizations to tmux status bar), HIST tweaks, tmux colors

diff --git a/home/.bashrc.d/ps1 b/home/.bashrc.d/ps1
--- a/home/.bashrc.d/ps1
+++ b/home/.bashrc.d/ps1
@@ -3,19 +3,29 @@
 # PS1 generator: https://xta.github.io/HalloweenBash/
 # TODO: use different colors for different datacenters/environments using VLANs
 
-USE_FORKED_LIQUIDPROMPT=true
+USE_FORKED_LIQUIDPROMPT=false
 USE_CLASSIC_PS1=false
 
-if [[ "${USE_FORKED_LIQUIDPROMPT}" == "true" && \
-! -f ~/.homesick/repos/liquidprompt/liquidprompt ]] ; then
-  echo "Could not find cloned liquidprompt fork. Rerun \"~/.workstation_setup.sh\"?"
-  echo "Using default \"${PS1}\"."
-elif [[ "${USE_FORKED_LIQUIDPROMPT}" == "true" && \
--f ~/.homesick/repos/liquidprompt/liquidprompt ]] ; then
-  # had to fork nojhan/liquidprompt until merges are made for:
-  #  bschwedler:feature/kubernetes-context, pull/476, etc.
-  [[ $- = *i* ]] && source ~/.homesick/repos/liquidprompt/liquidprompt
-else
+if [[ "${USE_FORKED_LIQUIDPROMPT}" == "true" ]]; then
+  if ! -f ~/.homesick/repos/liquidprompt/liquidprompt ]] ; then
+    echo "Could not find cloned liquidprompt fork. Rerun \"~/.workstation_setup.sh\"?"
+    echo "Using default \"${PS1}\"."
+  else
+    # had to fork nojhan/liquidprompt until merges are made for:
+    #  bschwedler:feature/kubernetes-context, pull/476, etc.
+    [[ $- = *i* ]] && source ~/.homesick/repos/liquidprompt/liquidprompt
+  fi
+elif [[ "${USE_FORKED_LIQUIDPROMPT}" == "false" && \
+  "${USE_CLASSIC_PS1}" == "false" ]]; then
+  if [[ -f /usr/local/share/liquidprompt ]]; then
+    # homebrew installation of nojhan/liquidprompt and standard customizations
+    [[ $- = *i* ]] && source /usr/local/share/liquidprompt
+    # using the prefix variable will only execute the inner function on new terminals
+    #  instead of every prompt display :(
+    # (using tmux status bar instead for kubernetes info) LP_PS1_PREFIX="$(_kube_ps1) "
+  fi
+fi
+if [[ "${USE_CLASSIC_PS1}"]]; then
   # declare some PS1 colors and helper functions
   NORMAL=$(tput sgr0)
   BOLD=$(tput bold)
@@ -53,27 +63,6 @@ else
     fi
   }
 
-  if [[ "${USE_CLASSIC_PS1}" == "true" ]] ; then
-    # PS1 Codes
-    # u - the current user's username
-    # h - the current machine's hostname
-    # j - the number of jobs managed by this shell
-    # @ - the current time (12 hour format)
-    # d - the current date
-    # w - path of the current working directory
-    # W - just the current working directory
-    # e - an ASCII escape character (033)
-    # n - adds a newline character
-    export PS1="\[${BOLD}\]\[${GREEN}\]\u@\h\[${BLUE}\] \w\[${BROWN}\]\[${BLUE}\]\$(_parse_git_branch)\$\[${NORMAL}\] "
-    PS1="\[${YELLOW}\]\$(_kube_ps1)\[${NORMAL}\]"$PS1
-  elif [[ -f /usr/local/share/liquidprompt ]]; then
-    # homebrew installation of nojhan/liquidprompt and standard customizations
-    . /usr/local/share/liquidprompt
-    # using the prefix variable will only execute the inner function on new terminals
-    #  instead of every prompt display :(
-    LP_PS1_PREFIX="$(_kube_ps1) "
-  else
-    echo "Could not find any customized PS1 information. Rerun \"~/.workstation_setup.sh\"?"
-    echo "Using default \"${PS1}\"."
-  fi
+  export PS1="\[${BOLD}\]\[${GREEN}\]\u@\h\[${BLUE}\] \w\[${BROWN}\]\[${BLUE}\]\$(_parse_git_branch)\$\[${NORMAL}\] "
+  PS1="\[${YELLOW}\]\$(_kube_ps1)\[${NORMAL}\]"$PS1
 fi
