rearranging files, moved path and alias earlier, hardcoding bsd ssh path for OSX, smarter about not being at work or home

diff --git a/home/.bashrc.d/work b/home/.bashrc.d/work
--- a/home/.bashrc.d/work
+++ b/home/.bashrc.d/work
@@ -1,10 +1,9 @@
 [[ $- = *i* ]] || return
 ${IS_OSX} || return
+${HEALTHY_INTERNET} || return
 
 # TODO: move most of this to a script called after login or screen-unlock
 #  https://stackoverflow.com/questions/6442364/running-script-upon-login-mac
-${HEALTHY_INTERNET} || return
-# set up network related profile
 
 # get network awareness
 ip_address=""
@@ -25,14 +24,13 @@ case ${ip_address} in
   ${CUSTOM_HOME_SUBNET}*)
     at_home="true" ;;
   *)
-    echo "Could not determine location from ip_address ${ip_address}."
-    # TODO: inject logic for what to do in non-work/non-home networks
+    echo "Could not determine location from ip_address ${ip_address}." ;;
 esac
 
 if ${at_home} ; then
-  # establish vpn connection to work
+  # prompt for vpn connection to work
   if ! $(ping -c1 -W1 -i0.1 laphroaig.${CUSTOM_WORK_DOMAINS[1]} &> /dev/null); then
-    (read -t 2 -s -p "To connect to work VPN, press any key within 2 seconds..." \
+    (read -t 1 -s -p "To connect to work VPN, press Enter key within 1 second..." \
       && lpass show --password --clip "AD" && \
       /opt/cisco/anyconnect/bin/vpn connect ${CUSTOM_WORK_DOMAINS[2]/\.*/} && pp
       echo && clear_clip
@@ -71,4 +69,17 @@ elif ${at_work} ; then
   # establish vpn connection to PGi
   # ping -c1 -w1 -i0.1 172.x.x.x > /dev/null || /opt/cisco/anyconnect/bin/vpn connect pgi
   # pkill "Google Photos Backup"
+else
+  echo
+  if ! $(ping -c1 -W1 -i0.1 laphroaig.${CUSTOM_WORK_DOMAINS[1]} &> /dev/null); then
+    (read -t 2 -s -p "Not at home or work; to connect to work VPN, press Enter key within 2 seconds..." \
+      && lpass show --password --clip "AD" && \
+      /opt/cisco/anyconnect/bin/vpn connect ${CUSTOM_WORK_DOMAINS[2]/\.*/} && pp
+      echo && clear_clip
+    )
+  fi
+  echo
+  read -t 2 -p "If in public location and need P.I.A. VPN, press Enter key within 2 seconds..." \
+    && open -a "Private Internet Access"
+  echo
 fi
