Smarter _create-proxy, move aria to linux, docker-login helper, fixed gitp, kops helpers, smarter ip_address grabbing, vpn cleanup, work setups, workstation update fixes

diff --git a/home/.bashrc.d/work b/home/.bashrc.d/work
--- a/home/.bashrc.d/work
+++ b/home/.bashrc.d/work
@@ -11,23 +11,20 @@ at_work="false"
 at_home="false"
 on_vpn="false"
 
-# look for VPN IP first
-ip_address=$(/sbin/ifconfig utun1 2> /dev/null | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}')
-if [[ -z ${ip_address} ]]; then
-  ip_address=$(/sbin/ifconfig en0 | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}')
-fi
+# grab all ip addresses
+ip_address=$(/sbin/ifconfig 2> /dev/null | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}')
 
 # figure out location
-case ${ip_address} in
-  ${CUSTOM_WORK_SUBNET}.26.*|${CUSTOM_WORK_SUBNET}.1.*)
-    at_work="true" ;;
-  ${CUSTOM_HOME_SUBNET}*)
-    at_home="true" ;;
-  ${CUSTOM_VPN_SUBNET}.*)
-    on_vpn="true" ;;
-  *)
-    echo "Could not determine location from ip_address ${ip_address}." ;;
-esac
+if [[ ${ip_address} =~ ${CUSTOM_WORK_SUBNET}.26.* ]] || \
+ [[ ${ip_address} =~ ${CUSTOM_WORK_SUBNET}.1.* ]]; then
+  at_work="true"
+elif [[ ${ip_address} =~ ${CUSTOM_VPN_SUBNET}.* ]]; then
+  on_vpn="true"
+elif [[ ${ip_address} =~ ${CUSTOM_HOME_SUBNET}* ]]; then
+  at_home="true"
+else
+  echo "Could not determine location from ip_address ${ip_address}."
+fi
 
 if ${at_home} ; then
   # prompt for vpn connection to work
@@ -47,11 +44,15 @@ if ${at_home} ; then
       ${CUSTOM_NAS_HOST}:/share/pictures ~/Pictures/share1
   fi
 elif ${at_work} ; then
-  # disconnect VPN connection if necessary (TODO: smarter detection if on VPN at home)
-  # killall -HUP "Endpoint Security VPN"
+  # disconnect any VPN connection
+  # pkill -f "Endpoint_Security_VPN"
+  # pkill -f "TrGui"
+  # pkill -f "TrGUI"
+  # sudo launchctl unload /Library/LaunchDaemons/com.checkpoint.epc.service.plist &&\
+  #   sudo kextunload  /System/Library/Extensions/cpfw.kext
   # establish SSH tunnel to home proxy
   lpass show --password --clip "proxy.${CUSTOM_NAS_HOST#*\.}"
-  _create_socks_proxy "home.${CUSTOM_HOME_DOMAIN}" "2000" "${LOGNAME/bar/}"
+  _create_socks_proxy "home.${CUSTOM_HOME_DOMAIN}" "2000" "${LOGNAME:0:5}"
 
   while $(mount | grep -q "Documents/share1") ; do
     sudo umount -fv -t nfs ${CUSTOM_NAS_HOST}:/share
@@ -66,13 +67,17 @@ elif ${on_vpn} ; then
   # establish SSH tunnel to home proxy
   lpass show --password --clip "proxy.${CUSTOM_NAS_HOST#*\.}"
   # TODO: curl gets "000" response code when on VPN
-  _create_socks_proxy "home.${CUSTOM_HOME_DOMAIN}" "2000" "${LOGNAME/bar/}"
+  # _create_socks_proxy "home.${CUSTOM_HOME_DOMAIN}" "2000" "${LOGNAME:0:5}"
 else
   echo
-  if ! $(ping -c1 -W1 -i0.1 laphroaig.${CUSTOM_WORK_DOMAINS[1]} &> /dev/null); then
-    (read -t 2 -s -p "Not at home or work; to connect to work VPN, press Enter key within 2 seconds..." \
-      && lpass show --password --clip "AD" && \
-      /opt/cisco/anyconnect/bin/vpn connect ${CUSTOM_WORK_DOMAINS[1]/\.*/} && pp
+  if ! $(ping -c1 -W1 -i0.1 chef-server.i.${CUSTOM_WORK_DOMAINS[0]} &> /dev/null); then
+    (
+      read -t 2 -s -p "Not at home or work; to connect to work VPN, press Enter key within 2 seconds..." \
+        && lpass show --password --clip "${CUSTOM_WORK_DOMAINS[0]/.com/} main (one login)" \
+        # && sudo launchctl load /Library/LaunchDaemons/com.checkpoint.epc.service.plist \
+        # && sudo kextload /System/Library/Extensions/cpfw.kext \
+        # && /Applications/Endpoint\ Security\ VPN.app/Contents/MacOS/Endpoint_Security_VPN 2>1 > /dev/null &
+      pp
       echo && clear_clip
     )
   fi
